//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilToolsPlantform.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OilToolsPlantformEntities : DbContext
    {
        public OilToolsPlantformEntities()
            : base("name=OilToolsPlantformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbCatF> tbCatF { get; set; }
        public DbSet<tbCatFPic> tbCatFPic { get; set; }
        public DbSet<tbCatS> tbCatS { get; set; }
        public DbSet<tbCatSPic> tbCatSPic { get; set; }
        public DbSet<tbPic> tbPic { get; set; }
        public DbSet<tbTool> tbTool { get; set; }
        public DbSet<tbToolDetail> tbToolDetail { get; set; }
        public DbSet<tbToolPic> tbToolPic { get; set; }
        public DbSet<tbUser> tbUser { get; set; }
        public DbSet<tbToken> tbToken { get; set; }
        public DbSet<tbOrg> tbOrg { get; set; }
        public DbSet<tbRole> tbRole { get; set; }
        public DbSet<tbRoleDetail> tbRoleDetail { get; set; }
        public DbSet<tbLog> tbLog { get; set; }
        public DbSet<tbCountAna> tbCountAna { get; set; }
        public DbSet<tbToolExt> tbToolExt { get; set; }
        public DbSet<tbWechatFan> tbWechatFan { get; set; }
        public DbSet<tbAudit> tbAudit { get; set; }
    }
}
