//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilToolsPlantform.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// tbAudit
    /// </summary>
    public partial class tbAudit
    {
    	/// <summary>
        /// 
        /// </summary>
        public int AuditID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string TargetTableName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int TargetTableID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int Status { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Status_Desc { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> AuditID1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AuditName1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> AuditStatus1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> AuditDate1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> AuditID2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AuditName2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> AuditStatus2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> AuditDate2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> AuditID3 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AuditName3 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> AuditStatus3 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> AuditDate3 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> AuditID4 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AuditName4 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> AuditStatus4 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> AuditDate4 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> AuditID5 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AuditName5 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> AuditStatus5 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> AuditDate5 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> NextAuditOrgID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string LastAuditName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> LastAuditDate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> NextAuditStep { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AuditAdvice1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AuditAdvice2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AuditAdvice3 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AuditAdvice4 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AuditAdvice5 { get; set; }
    }
}
