//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilToolsPlantform.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// tbCatSPic
    /// </summary>
    public partial class tbCatSPic
    {
    	/// <summary>
        /// 
        /// </summary>
        public int CatSPicID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int CatSID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int PicID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string PicType { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int SortOrder { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Enabled { get; set; }
    
        public virtual tbCatS tbCatS { get; set; }
        public virtual tbPic tbPic { get; set; }
    }
}
