//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilToolsPlantform.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// tbCountAna
    /// </summary>
    public partial class tbCountAna
    {
    	/// <summary>
        /// 
        /// </summary>
        public int CountAnaID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public System.DateTime Day { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int ToolAdd { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int FanAdd { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int ViewAdd { get; set; }
    }
}
