//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilToolsPlantform.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// tbLog
    /// </summary>
    public partial class tbLog
    {
    	/// <summary>
        /// 
        /// </summary>
        public int LogID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AccountNumber { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> UserID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Request { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Response { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Description { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> HappenDate { get; set; }
    }
}
