//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilToolsPlantform.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// tbPic
    /// </summary>
    public partial class tbPic
    {
        public tbPic()
        {
            this.tbCatFPic = new HashSet<tbCatFPic>();
            this.tbCatSPic = new HashSet<tbCatSPic>();
            this.tbToolPic = new HashSet<tbToolPic>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
        public int PicID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string PicName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string StoreName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Path { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string ThambName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string CreateUser { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<tbCatFPic> tbCatFPic { get; set; }
        public virtual ICollection<tbCatSPic> tbCatSPic { get; set; }
        public virtual ICollection<tbToolPic> tbToolPic { get; set; }
    }
}
