//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilToolsPlantform.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// tbRoleDetail
    /// </summary>
    public partial class tbRoleDetail
    {
    	/// <summary>
        /// 
        /// </summary>
        public int RoleDetailID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> RoleID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FunctionCode { get; set; }
    
        public virtual tbRole tbRole { get; set; }
    }
}
