//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilToolsPlantform.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// tbRole
    /// </summary>
    public partial class tbRole
    {
        public tbRole()
        {
            this.tbUser = new HashSet<tbUser>();
            this.tbRoleDetail = new HashSet<tbRoleDetail>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
        public int RoleID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string RoleName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string RoleType { get; set; }
    
        public virtual ICollection<tbUser> tbUser { get; set; }
        public virtual ICollection<tbRoleDetail> tbRoleDetail { get; set; }
    }
}
