//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilToolsPlantform.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// tbToolDetail
    /// </summary>
    public partial class tbToolDetail
    {
    	/// <summary>
        /// 
        /// </summary>
        public int ToolDetailID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int ToolID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int DetailIcon { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string IconName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string NameJP { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string NameQP { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Description { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string CreateUser { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string UpdateUser { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public System.DateTime UpdateTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int SortOrder { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Enabled { get; set; }
    
        public virtual tbTool tbTool { get; set; }
    }
}
