//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilToolsPlantform.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// tbToolExt
    /// </summary>
    public partial class tbToolExt
    {
    	/// <summary>
        /// 
        /// </summary>
        public int ToolExtID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int ToolID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int ViewCount { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int LikeCount { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int FavCount { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int CommentCount { get; set; }
    
        public virtual tbTool tbTool { get; set; }
    }
}
