//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilToolsPlantform.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// tbUser
    /// </summary>
    public partial class tbUser
    {
    	/// <summary>
        /// 
        /// </summary>
        public int UserID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string UserAccount { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string UserPass { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Salt { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public System.DateTime StartDate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public System.DateTime EndDate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> LastLoginTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public System.DateTime UpdateTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Enabled { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> OrgID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string CellPhone { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Email { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string WorkNumber { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> RoleID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string UserName { get; set; }
    
        public virtual tbOrg tbOrg { get; set; }
        public virtual tbRole tbRole { get; set; }
    }
}
