//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilToolsPlantform.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// tbWechatFan
    /// </summary>
    public partial class tbWechatFan
    {
    	/// <summary>
        /// 
        /// </summary>
        public int WechatFanID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string openid { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string subscribe { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string nickname { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string sex { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string city { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string country { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string province { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string language { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string headimgurl { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string subscribe_time { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string unionid { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string remark { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string groupid { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string tagid_list { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string subscribe_scene { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string qr_scene { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string qr_scene_str { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public System.DateTime updatetime { get; set; }
    }
}
